module.exports = {
  apps: [
    {
      name: "getfastcalc-telegram-bot",
      script: "scripts/seo/telegram_bot.py",
      interpreter: "scripts/seo/.venv/bin/python3",
      cwd: "/Users/aicommander/CascadeProjects/toolcalc",
      env: {
        NODE_ENV: "production",
        PYTHONUNBUFFERED: "1",
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      log_file: "./logs/pm2/combined.log",
      out_file: "./logs/pm2/out.log",
      error_file: "./logs/pm2/error.log",
      time: true,
      watch: false,
      max_memory_restart: "512M",
    },
    {
      name: "getfastcalc-link-exchange",
      script: "scripts/link-exchange/server.py",
      interpreter: "scripts/seo/.venv/bin/python3",
      cwd: "/Users/aicommander/CascadeProjects/toolcalc",
      env: {
        PYTHONUNBUFFERED: "1",
        LINK_EXCHANGE_PORT: "5312",
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      log_file: "./logs/pm2/link-exchange.log",
      out_file: "./logs/pm2/link-exchange-out.log",
      error_file: "./logs/pm2/link-exchange-error.log",
      time: true,
      watch: false,
      max_memory_restart: "512M",
    },
  ],
};
